import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import Card from '../components/Card';
import Filter from '../components/Filter';
import styles from '../styles/Home.module.css'

export async function getStaticProps (context) {
  const res = await axios.get(`https://api.themoviedb.org/3/movie/upcoming?api_key=${process.env.NEXT_PUBLIC_TMDB}&language=en-US&page=1`);

  return {
    props: { 
      data: res.data.results || null,
      revalidate: 100,
    },
  };
}

export default function Home({ data }) {
  const [queue, setQueue] = useState(data || null);
  const [filter, setFilter] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Checkout Current <a href="https://nextjs.org">Movies</a>
        </h1>

        <div className={styles.prompt}>
          <p className={styles.description}>
            It all starts here:{' '}
            {/* <code className={styles.code}>Down Below</code> */}
          </p>
          <Filter data={data} filter={filter} setFilter={setFilter} setQueue={setQueue} />
        </div>

        <div className={styles.grid}>
          {queue?.map((movie, key) => {
            if(movie?.original_language === 'en') {
              return(
                <Card movie={movie} key={key} />
              );
            }
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
